//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueCurve.Dataloader.AM.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="agg_results", Namespace="http://schemas.datacontract.org/2004/07/BlueCurve.IIS.Services")]
    [System.SerializableAttribute()]
    public partial class agg_results : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlueCurve.Dataloader.AM.ServiceReference1.abc_calc_agg[] abc_calc_aggField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlueCurve.Dataloader.AM.ServiceReference1.abc_calc_agg[] abc_calc_agg_ccField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlueCurve.Dataloader.AM.ServiceReference1.abc_calc_agg[] abc_calc_agg_growthsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlueCurve.Dataloader.AM.ServiceReference1.agg_result[] resultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BlueCurve.Dataloader.AM.ServiceReference1.ttest_result[] ttestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlueCurve.Dataloader.AM.ServiceReference1.abc_calc_agg[] abc_calc_agg {
            get {
                return this.abc_calc_aggField;
            }
            set {
                if ((object.ReferenceEquals(this.abc_calc_aggField, value) != true)) {
                    this.abc_calc_aggField = value;
                    this.RaisePropertyChanged("abc_calc_agg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlueCurve.Dataloader.AM.ServiceReference1.abc_calc_agg[] abc_calc_agg_cc {
            get {
                return this.abc_calc_agg_ccField;
            }
            set {
                if ((object.ReferenceEquals(this.abc_calc_agg_ccField, value) != true)) {
                    this.abc_calc_agg_ccField = value;
                    this.RaisePropertyChanged("abc_calc_agg_cc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlueCurve.Dataloader.AM.ServiceReference1.abc_calc_agg[] abc_calc_agg_growths {
            get {
                return this.abc_calc_agg_growthsField;
            }
            set {
                if ((object.ReferenceEquals(this.abc_calc_agg_growthsField, value) != true)) {
                    this.abc_calc_agg_growthsField = value;
                    this.RaisePropertyChanged("abc_calc_agg_growths");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error {
            get {
                return this.errorField;
            }
            set {
                if ((object.ReferenceEquals(this.errorField, value) != true)) {
                    this.errorField = value;
                    this.RaisePropertyChanged("error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlueCurve.Dataloader.AM.ServiceReference1.agg_result[] results {
            get {
                return this.resultsField;
            }
            set {
                if ((object.ReferenceEquals(this.resultsField, value) != true)) {
                    this.resultsField = value;
                    this.RaisePropertyChanged("results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BlueCurve.Dataloader.AM.ServiceReference1.ttest_result[] ttest {
            get {
                return this.ttestField;
            }
            set {
                if ((object.ReferenceEquals(this.ttestField, value) != true)) {
                    this.ttestField = value;
                    this.RaisePropertyChanged("ttest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="abc_calc_agg", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class abc_calc_agg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long calculation_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int calenderized_year_offsetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long class_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long contributor_1_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long contributor_2_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int contributor_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long dual_entity_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long entity_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long host_curr_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool include_in_growthlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool include_in_growthrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intervalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int interval_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int item_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int num_yearsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int op1_curr_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int op2_curr_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int op3_curr_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int op4_curr_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int op5_curr_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int op6_curr_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int op7_curr_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int op8_curr_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long operand_1_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool operand_1_is_weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long operand_2_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool operand_2_is_weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long operand_3_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool operand_3_is_weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long operand_4_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool operand_4_is_weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long operand_5_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool operand_5_is_weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long operand_6_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool operand_6_is_weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long operand_7_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool operand_7_is_weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long operand_8_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool operand_8_is_weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long parent_entity_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime period_end_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int period_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_1_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_2_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_3_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_4_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_5_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_6_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_7_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> raw_value_8_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long result_row_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long target_entity_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> value_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> value_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> value_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> value_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> value_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> value_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> value_7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> value_8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> value_8_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> weightingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int workflow_stageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long calculation_id {
            get {
                return this.calculation_idField;
            }
            set {
                if ((this.calculation_idField.Equals(value) != true)) {
                    this.calculation_idField = value;
                    this.RaisePropertyChanged("calculation_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int calenderized_year_offset {
            get {
                return this.calenderized_year_offsetField;
            }
            set {
                if ((this.calenderized_year_offsetField.Equals(value) != true)) {
                    this.calenderized_year_offsetField = value;
                    this.RaisePropertyChanged("calenderized_year_offset");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long class_id {
            get {
                return this.class_idField;
            }
            set {
                if ((this.class_idField.Equals(value) != true)) {
                    this.class_idField = value;
                    this.RaisePropertyChanged("class_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long contributor_1_id {
            get {
                return this.contributor_1_idField;
            }
            set {
                if ((this.contributor_1_idField.Equals(value) != true)) {
                    this.contributor_1_idField = value;
                    this.RaisePropertyChanged("contributor_1_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long contributor_2_id {
            get {
                return this.contributor_2_idField;
            }
            set {
                if ((this.contributor_2_idField.Equals(value) != true)) {
                    this.contributor_2_idField = value;
                    this.RaisePropertyChanged("contributor_2_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int contributor_id {
            get {
                return this.contributor_idField;
            }
            set {
                if ((this.contributor_idField.Equals(value) != true)) {
                    this.contributor_idField = value;
                    this.RaisePropertyChanged("contributor_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long dual_entity_id {
            get {
                return this.dual_entity_idField;
            }
            set {
                if ((this.dual_entity_idField.Equals(value) != true)) {
                    this.dual_entity_idField = value;
                    this.RaisePropertyChanged("dual_entity_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long entity_id {
            get {
                return this.entity_idField;
            }
            set {
                if ((this.entity_idField.Equals(value) != true)) {
                    this.entity_idField = value;
                    this.RaisePropertyChanged("entity_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formula {
            get {
                return this.formulaField;
            }
            set {
                if ((object.ReferenceEquals(this.formulaField, value) != true)) {
                    this.formulaField = value;
                    this.RaisePropertyChanged("formula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long host_curr_id {
            get {
                return this.host_curr_idField;
            }
            set {
                if ((this.host_curr_idField.Equals(value) != true)) {
                    this.host_curr_idField = value;
                    this.RaisePropertyChanged("host_curr_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool include_in_growthl {
            get {
                return this.include_in_growthlField;
            }
            set {
                if ((this.include_in_growthlField.Equals(value) != true)) {
                    this.include_in_growthlField = value;
                    this.RaisePropertyChanged("include_in_growthl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool include_in_growthr {
            get {
                return this.include_in_growthrField;
            }
            set {
                if ((this.include_in_growthrField.Equals(value) != true)) {
                    this.include_in_growthrField = value;
                    this.RaisePropertyChanged("include_in_growthr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interval {
            get {
                return this.intervalField;
            }
            set {
                if ((this.intervalField.Equals(value) != true)) {
                    this.intervalField = value;
                    this.RaisePropertyChanged("interval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interval_type {
            get {
                return this.interval_typeField;
            }
            set {
                if ((this.interval_typeField.Equals(value) != true)) {
                    this.interval_typeField = value;
                    this.RaisePropertyChanged("interval_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int item_id {
            get {
                return this.item_idField;
            }
            set {
                if ((this.item_idField.Equals(value) != true)) {
                    this.item_idField = value;
                    this.RaisePropertyChanged("item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num_years {
            get {
                return this.num_yearsField;
            }
            set {
                if ((this.num_yearsField.Equals(value) != true)) {
                    this.num_yearsField = value;
                    this.RaisePropertyChanged("num_years");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int op1_curr_type {
            get {
                return this.op1_curr_typeField;
            }
            set {
                if ((this.op1_curr_typeField.Equals(value) != true)) {
                    this.op1_curr_typeField = value;
                    this.RaisePropertyChanged("op1_curr_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int op2_curr_type {
            get {
                return this.op2_curr_typeField;
            }
            set {
                if ((this.op2_curr_typeField.Equals(value) != true)) {
                    this.op2_curr_typeField = value;
                    this.RaisePropertyChanged("op2_curr_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int op3_curr_type {
            get {
                return this.op3_curr_typeField;
            }
            set {
                if ((this.op3_curr_typeField.Equals(value) != true)) {
                    this.op3_curr_typeField = value;
                    this.RaisePropertyChanged("op3_curr_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int op4_curr_type {
            get {
                return this.op4_curr_typeField;
            }
            set {
                if ((this.op4_curr_typeField.Equals(value) != true)) {
                    this.op4_curr_typeField = value;
                    this.RaisePropertyChanged("op4_curr_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int op5_curr_type {
            get {
                return this.op5_curr_typeField;
            }
            set {
                if ((this.op5_curr_typeField.Equals(value) != true)) {
                    this.op5_curr_typeField = value;
                    this.RaisePropertyChanged("op5_curr_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int op6_curr_type {
            get {
                return this.op6_curr_typeField;
            }
            set {
                if ((this.op6_curr_typeField.Equals(value) != true)) {
                    this.op6_curr_typeField = value;
                    this.RaisePropertyChanged("op6_curr_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int op7_curr_type {
            get {
                return this.op7_curr_typeField;
            }
            set {
                if ((this.op7_curr_typeField.Equals(value) != true)) {
                    this.op7_curr_typeField = value;
                    this.RaisePropertyChanged("op7_curr_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int op8_curr_type {
            get {
                return this.op8_curr_typeField;
            }
            set {
                if ((this.op8_curr_typeField.Equals(value) != true)) {
                    this.op8_curr_typeField = value;
                    this.RaisePropertyChanged("op8_curr_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long operand_1_id {
            get {
                return this.operand_1_idField;
            }
            set {
                if ((this.operand_1_idField.Equals(value) != true)) {
                    this.operand_1_idField = value;
                    this.RaisePropertyChanged("operand_1_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool operand_1_is_weight {
            get {
                return this.operand_1_is_weightField;
            }
            set {
                if ((this.operand_1_is_weightField.Equals(value) != true)) {
                    this.operand_1_is_weightField = value;
                    this.RaisePropertyChanged("operand_1_is_weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long operand_2_id {
            get {
                return this.operand_2_idField;
            }
            set {
                if ((this.operand_2_idField.Equals(value) != true)) {
                    this.operand_2_idField = value;
                    this.RaisePropertyChanged("operand_2_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool operand_2_is_weight {
            get {
                return this.operand_2_is_weightField;
            }
            set {
                if ((this.operand_2_is_weightField.Equals(value) != true)) {
                    this.operand_2_is_weightField = value;
                    this.RaisePropertyChanged("operand_2_is_weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long operand_3_id {
            get {
                return this.operand_3_idField;
            }
            set {
                if ((this.operand_3_idField.Equals(value) != true)) {
                    this.operand_3_idField = value;
                    this.RaisePropertyChanged("operand_3_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool operand_3_is_weight {
            get {
                return this.operand_3_is_weightField;
            }
            set {
                if ((this.operand_3_is_weightField.Equals(value) != true)) {
                    this.operand_3_is_weightField = value;
                    this.RaisePropertyChanged("operand_3_is_weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long operand_4_id {
            get {
                return this.operand_4_idField;
            }
            set {
                if ((this.operand_4_idField.Equals(value) != true)) {
                    this.operand_4_idField = value;
                    this.RaisePropertyChanged("operand_4_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool operand_4_is_weight {
            get {
                return this.operand_4_is_weightField;
            }
            set {
                if ((this.operand_4_is_weightField.Equals(value) != true)) {
                    this.operand_4_is_weightField = value;
                    this.RaisePropertyChanged("operand_4_is_weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long operand_5_id {
            get {
                return this.operand_5_idField;
            }
            set {
                if ((this.operand_5_idField.Equals(value) != true)) {
                    this.operand_5_idField = value;
                    this.RaisePropertyChanged("operand_5_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool operand_5_is_weight {
            get {
                return this.operand_5_is_weightField;
            }
            set {
                if ((this.operand_5_is_weightField.Equals(value) != true)) {
                    this.operand_5_is_weightField = value;
                    this.RaisePropertyChanged("operand_5_is_weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long operand_6_id {
            get {
                return this.operand_6_idField;
            }
            set {
                if ((this.operand_6_idField.Equals(value) != true)) {
                    this.operand_6_idField = value;
                    this.RaisePropertyChanged("operand_6_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool operand_6_is_weight {
            get {
                return this.operand_6_is_weightField;
            }
            set {
                if ((this.operand_6_is_weightField.Equals(value) != true)) {
                    this.operand_6_is_weightField = value;
                    this.RaisePropertyChanged("operand_6_is_weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long operand_7_id {
            get {
                return this.operand_7_idField;
            }
            set {
                if ((this.operand_7_idField.Equals(value) != true)) {
                    this.operand_7_idField = value;
                    this.RaisePropertyChanged("operand_7_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool operand_7_is_weight {
            get {
                return this.operand_7_is_weightField;
            }
            set {
                if ((this.operand_7_is_weightField.Equals(value) != true)) {
                    this.operand_7_is_weightField = value;
                    this.RaisePropertyChanged("operand_7_is_weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long operand_8_id {
            get {
                return this.operand_8_idField;
            }
            set {
                if ((this.operand_8_idField.Equals(value) != true)) {
                    this.operand_8_idField = value;
                    this.RaisePropertyChanged("operand_8_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool operand_8_is_weight {
            get {
                return this.operand_8_is_weightField;
            }
            set {
                if ((this.operand_8_is_weightField.Equals(value) != true)) {
                    this.operand_8_is_weightField = value;
                    this.RaisePropertyChanged("operand_8_is_weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parent_entity_id {
            get {
                return this.parent_entity_idField;
            }
            set {
                if ((this.parent_entity_idField.Equals(value) != true)) {
                    this.parent_entity_idField = value;
                    this.RaisePropertyChanged("parent_entity_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime period_end_date {
            get {
                return this.period_end_dateField;
            }
            set {
                if ((this.period_end_dateField.Equals(value) != true)) {
                    this.period_end_dateField = value;
                    this.RaisePropertyChanged("period_end_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int period_id {
            get {
                return this.period_idField;
            }
            set {
                if ((this.period_idField.Equals(value) != true)) {
                    this.period_idField = value;
                    this.RaisePropertyChanged("period_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_1 {
            get {
                return this.raw_value_1Field;
            }
            set {
                if ((this.raw_value_1Field.Equals(value) != true)) {
                    this.raw_value_1Field = value;
                    this.RaisePropertyChanged("raw_value_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_1_1 {
            get {
                return this.raw_value_1_1Field;
            }
            set {
                if ((this.raw_value_1_1Field.Equals(value) != true)) {
                    this.raw_value_1_1Field = value;
                    this.RaisePropertyChanged("raw_value_1_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_2 {
            get {
                return this.raw_value_2Field;
            }
            set {
                if ((this.raw_value_2Field.Equals(value) != true)) {
                    this.raw_value_2Field = value;
                    this.RaisePropertyChanged("raw_value_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_2_1 {
            get {
                return this.raw_value_2_1Field;
            }
            set {
                if ((this.raw_value_2_1Field.Equals(value) != true)) {
                    this.raw_value_2_1Field = value;
                    this.RaisePropertyChanged("raw_value_2_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_3 {
            get {
                return this.raw_value_3Field;
            }
            set {
                if ((this.raw_value_3Field.Equals(value) != true)) {
                    this.raw_value_3Field = value;
                    this.RaisePropertyChanged("raw_value_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_3_1 {
            get {
                return this.raw_value_3_1Field;
            }
            set {
                if ((this.raw_value_3_1Field.Equals(value) != true)) {
                    this.raw_value_3_1Field = value;
                    this.RaisePropertyChanged("raw_value_3_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_4 {
            get {
                return this.raw_value_4Field;
            }
            set {
                if ((this.raw_value_4Field.Equals(value) != true)) {
                    this.raw_value_4Field = value;
                    this.RaisePropertyChanged("raw_value_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_4_1 {
            get {
                return this.raw_value_4_1Field;
            }
            set {
                if ((this.raw_value_4_1Field.Equals(value) != true)) {
                    this.raw_value_4_1Field = value;
                    this.RaisePropertyChanged("raw_value_4_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_5 {
            get {
                return this.raw_value_5Field;
            }
            set {
                if ((this.raw_value_5Field.Equals(value) != true)) {
                    this.raw_value_5Field = value;
                    this.RaisePropertyChanged("raw_value_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_5_1 {
            get {
                return this.raw_value_5_1Field;
            }
            set {
                if ((this.raw_value_5_1Field.Equals(value) != true)) {
                    this.raw_value_5_1Field = value;
                    this.RaisePropertyChanged("raw_value_5_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_6 {
            get {
                return this.raw_value_6Field;
            }
            set {
                if ((this.raw_value_6Field.Equals(value) != true)) {
                    this.raw_value_6Field = value;
                    this.RaisePropertyChanged("raw_value_6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_6_1 {
            get {
                return this.raw_value_6_1Field;
            }
            set {
                if ((this.raw_value_6_1Field.Equals(value) != true)) {
                    this.raw_value_6_1Field = value;
                    this.RaisePropertyChanged("raw_value_6_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_7 {
            get {
                return this.raw_value_7Field;
            }
            set {
                if ((this.raw_value_7Field.Equals(value) != true)) {
                    this.raw_value_7Field = value;
                    this.RaisePropertyChanged("raw_value_7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_7_1 {
            get {
                return this.raw_value_7_1Field;
            }
            set {
                if ((this.raw_value_7_1Field.Equals(value) != true)) {
                    this.raw_value_7_1Field = value;
                    this.RaisePropertyChanged("raw_value_7_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_8 {
            get {
                return this.raw_value_8Field;
            }
            set {
                if ((this.raw_value_8Field.Equals(value) != true)) {
                    this.raw_value_8Field = value;
                    this.RaisePropertyChanged("raw_value_8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> raw_value_8_1 {
            get {
                return this.raw_value_8_1Field;
            }
            set {
                if ((this.raw_value_8_1Field.Equals(value) != true)) {
                    this.raw_value_8_1Field = value;
                    this.RaisePropertyChanged("raw_value_8_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long result_row_id {
            get {
                return this.result_row_idField;
            }
            set {
                if ((this.result_row_idField.Equals(value) != true)) {
                    this.result_row_idField = value;
                    this.RaisePropertyChanged("result_row_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long target_entity_id {
            get {
                return this.target_entity_idField;
            }
            set {
                if ((this.target_entity_idField.Equals(value) != true)) {
                    this.target_entity_idField = value;
                    this.RaisePropertyChanged("target_entity_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value_1 {
            get {
                return this.value_1Field;
            }
            set {
                if ((this.value_1Field.Equals(value) != true)) {
                    this.value_1Field = value;
                    this.RaisePropertyChanged("value_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value_2 {
            get {
                return this.value_2Field;
            }
            set {
                if ((this.value_2Field.Equals(value) != true)) {
                    this.value_2Field = value;
                    this.RaisePropertyChanged("value_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value_3 {
            get {
                return this.value_3Field;
            }
            set {
                if ((this.value_3Field.Equals(value) != true)) {
                    this.value_3Field = value;
                    this.RaisePropertyChanged("value_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value_4 {
            get {
                return this.value_4Field;
            }
            set {
                if ((this.value_4Field.Equals(value) != true)) {
                    this.value_4Field = value;
                    this.RaisePropertyChanged("value_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value_5 {
            get {
                return this.value_5Field;
            }
            set {
                if ((this.value_5Field.Equals(value) != true)) {
                    this.value_5Field = value;
                    this.RaisePropertyChanged("value_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value_6 {
            get {
                return this.value_6Field;
            }
            set {
                if ((this.value_6Field.Equals(value) != true)) {
                    this.value_6Field = value;
                    this.RaisePropertyChanged("value_6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value_7 {
            get {
                return this.value_7Field;
            }
            set {
                if ((this.value_7Field.Equals(value) != true)) {
                    this.value_7Field = value;
                    this.RaisePropertyChanged("value_7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value_8 {
            get {
                return this.value_8Field;
            }
            set {
                if ((this.value_8Field.Equals(value) != true)) {
                    this.value_8Field = value;
                    this.RaisePropertyChanged("value_8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value_8_1 {
            get {
                return this.value_8_1Field;
            }
            set {
                if ((this.value_8_1Field.Equals(value) != true)) {
                    this.value_8_1Field = value;
                    this.RaisePropertyChanged("value_8_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> weighting {
            get {
                return this.weightingField;
            }
            set {
                if ((this.weightingField.Equals(value) != true)) {
                    this.weightingField = value;
                    this.RaisePropertyChanged("weighting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int workflow_stage {
            get {
                return this.workflow_stageField;
            }
            set {
                if ((this.workflow_stageField.Equals(value) != true)) {
                    this.workflow_stageField = value;
                    this.RaisePropertyChanged("workflow_stage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int year {
            get {
                return this.yearField;
            }
            set {
                if ((this.yearField.Equals(value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="agg_result", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class agg_result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long audit_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long contributor_1_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long contributor_2_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int contributor_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long currencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long dual_entity_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int exch_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long item_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> lvalueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int num_yearsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int period_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> rvalueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long target_entity_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long universe_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> valueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int workflow_stageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long audit_id {
            get {
                return this.audit_idField;
            }
            set {
                if ((this.audit_idField.Equals(value) != true)) {
                    this.audit_idField = value;
                    this.RaisePropertyChanged("audit_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long contributor_1_id {
            get {
                return this.contributor_1_idField;
            }
            set {
                if ((this.contributor_1_idField.Equals(value) != true)) {
                    this.contributor_1_idField = value;
                    this.RaisePropertyChanged("contributor_1_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long contributor_2_id {
            get {
                return this.contributor_2_idField;
            }
            set {
                if ((this.contributor_2_idField.Equals(value) != true)) {
                    this.contributor_2_idField = value;
                    this.RaisePropertyChanged("contributor_2_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int contributor_id {
            get {
                return this.contributor_idField;
            }
            set {
                if ((this.contributor_idField.Equals(value) != true)) {
                    this.contributor_idField = value;
                    this.RaisePropertyChanged("contributor_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long currency {
            get {
                return this.currencyField;
            }
            set {
                if ((this.currencyField.Equals(value) != true)) {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long dual_entity_id {
            get {
                return this.dual_entity_idField;
            }
            set {
                if ((this.dual_entity_idField.Equals(value) != true)) {
                    this.dual_entity_idField = value;
                    this.RaisePropertyChanged("dual_entity_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int exch_type {
            get {
                return this.exch_typeField;
            }
            set {
                if ((this.exch_typeField.Equals(value) != true)) {
                    this.exch_typeField = value;
                    this.RaisePropertyChanged("exch_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long item_id {
            get {
                return this.item_idField;
            }
            set {
                if ((this.item_idField.Equals(value) != true)) {
                    this.item_idField = value;
                    this.RaisePropertyChanged("item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> lvalue {
            get {
                return this.lvalueField;
            }
            set {
                if ((this.lvalueField.Equals(value) != true)) {
                    this.lvalueField = value;
                    this.RaisePropertyChanged("lvalue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num_years {
            get {
                return this.num_yearsField;
            }
            set {
                if ((this.num_yearsField.Equals(value) != true)) {
                    this.num_yearsField = value;
                    this.RaisePropertyChanged("num_years");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int period_id {
            get {
                return this.period_idField;
            }
            set {
                if ((this.period_idField.Equals(value) != true)) {
                    this.period_idField = value;
                    this.RaisePropertyChanged("period_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> rvalue {
            get {
                return this.rvalueField;
            }
            set {
                if ((this.rvalueField.Equals(value) != true)) {
                    this.rvalueField = value;
                    this.RaisePropertyChanged("rvalue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long target_entity_id {
            get {
                return this.target_entity_idField;
            }
            set {
                if ((this.target_entity_idField.Equals(value) != true)) {
                    this.target_entity_idField = value;
                    this.RaisePropertyChanged("target_entity_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long universe_id {
            get {
                return this.universe_idField;
            }
            set {
                if ((this.universe_idField.Equals(value) != true)) {
                    this.universe_idField = value;
                    this.RaisePropertyChanged("universe_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> value {
            get {
                return this.valueField;
            }
            set {
                if ((this.valueField.Equals(value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int workflow_stage {
            get {
                return this.workflow_stageField;
            }
            set {
                if ((this.workflow_stageField.Equals(value) != true)) {
                    this.workflow_stageField = value;
                    this.RaisePropertyChanged("workflow_stage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int year {
            get {
                return this.yearField;
            }
            set {
                if ((this.yearField.Equals(value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ttest_result", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class ttest_result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int contributor_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double eff_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long item_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal meanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int num_pointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int period_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double sd3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double standard_deviationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double standard_deviation_multField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string style_calculation_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal total_weightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double weighted_meanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int workflow_stageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int yearField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int contributor_id {
            get {
                return this.contributor_idField;
            }
            set {
                if ((this.contributor_idField.Equals(value) != true)) {
                    this.contributor_idField = value;
                    this.RaisePropertyChanged("contributor_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double eff_number {
            get {
                return this.eff_numberField;
            }
            set {
                if ((this.eff_numberField.Equals(value) != true)) {
                    this.eff_numberField = value;
                    this.RaisePropertyChanged("eff_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long item_id {
            get {
                return this.item_idField;
            }
            set {
                if ((this.item_idField.Equals(value) != true)) {
                    this.item_idField = value;
                    this.RaisePropertyChanged("item_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal mean {
            get {
                return this.meanField;
            }
            set {
                if ((this.meanField.Equals(value) != true)) {
                    this.meanField = value;
                    this.RaisePropertyChanged("mean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int num_points {
            get {
                return this.num_pointsField;
            }
            set {
                if ((this.num_pointsField.Equals(value) != true)) {
                    this.num_pointsField = value;
                    this.RaisePropertyChanged("num_points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int period_id {
            get {
                return this.period_idField;
            }
            set {
                if ((this.period_idField.Equals(value) != true)) {
                    this.period_idField = value;
                    this.RaisePropertyChanged("period_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double sd3 {
            get {
                return this.sd3Field;
            }
            set {
                if ((this.sd3Field.Equals(value) != true)) {
                    this.sd3Field = value;
                    this.RaisePropertyChanged("sd3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double standard_deviation {
            get {
                return this.standard_deviationField;
            }
            set {
                if ((this.standard_deviationField.Equals(value) != true)) {
                    this.standard_deviationField = value;
                    this.RaisePropertyChanged("standard_deviation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double standard_deviation_mult {
            get {
                return this.standard_deviation_multField;
            }
            set {
                if ((this.standard_deviation_multField.Equals(value) != true)) {
                    this.standard_deviation_multField = value;
                    this.RaisePropertyChanged("standard_deviation_mult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string style_calculation_type {
            get {
                return this.style_calculation_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.style_calculation_typeField, value) != true)) {
                    this.style_calculation_typeField = value;
                    this.RaisePropertyChanged("style_calculation_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal total_weight {
            get {
                return this.total_weightField;
            }
            set {
                if ((this.total_weightField.Equals(value) != true)) {
                    this.total_weightField = value;
                    this.RaisePropertyChanged("total_weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double weighted_mean {
            get {
                return this.weighted_meanField;
            }
            set {
                if ((this.weighted_meanField.Equals(value) != true)) {
                    this.weighted_meanField = value;
                    this.RaisePropertyChanged("weighted_mean");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int workflow_stage {
            get {
                return this.workflow_stageField;
            }
            set {
                if ((this.workflow_stageField.Equals(value) != true)) {
                    this.workflow_stageField = value;
                    this.RaisePropertyChanged("workflow_stage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int year {
            get {
                return this.yearField;
            }
            set {
                if ((this.yearField.Equals(value) != true)) {
                    this.yearField = value;
                    this.RaisePropertyChanged("year");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBCIISServices")]
    public interface IBCIISServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCIISServices/AggregateUniverse", ReplyAction="http://tempuri.org/IBCIISServices/AggregateUniverseResponse")]
        string AggregateUniverse(long run_id, long universe_id, int audit_id, System.DateTime audit_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCIISServices/AggregateUniverse", ReplyAction="http://tempuri.org/IBCIISServices/AggregateUniverseResponse")]
        System.Threading.Tasks.Task<string> AggregateUniverseAsync(long run_id, long universe_id, int audit_id, System.DateTime audit_date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCIISServices/AggregateUniverseDebug", ReplyAction="http://tempuri.org/IBCIISServices/AggregateUniverseDebugResponse")]
        BlueCurve.Dataloader.AM.ServiceReference1.agg_results AggregateUniverseDebug(long run_id, long universe_id, int audit_id, System.DateTime audit_date, long target_entity_id, long dual_entity_id, int debug_exch_method, string debug_calc_type, bool inc_constituents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCIISServices/AggregateUniverseDebug", ReplyAction="http://tempuri.org/IBCIISServices/AggregateUniverseDebugResponse")]
        System.Threading.Tasks.Task<BlueCurve.Dataloader.AM.ServiceReference1.agg_results> AggregateUniverseDebugAsync(long run_id, long universe_id, int audit_id, System.DateTime audit_date, long target_entity_id, long dual_entity_id, int debug_exch_method, string debug_calc_type, bool inc_constituents);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCIISServices/CalcAll", ReplyAction="http://tempuri.org/IBCIISServices/CalcAllResponse")]
        string CalcAll(long run_id, long entity_id, int audit_id, System.DateTime audit_date, int contributor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCIISServices/CalcAll", ReplyAction="http://tempuri.org/IBCIISServices/CalcAllResponse")]
        System.Threading.Tasks.Task<string> CalcAllAsync(long run_id, long entity_id, int audit_id, System.DateTime audit_date, int contributor_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCIISServices/RunTask", ReplyAction="http://tempuri.org/IBCIISServices/RunTaskResponse")]
        string RunTask(int task_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBCIISServices/RunTask", ReplyAction="http://tempuri.org/IBCIISServices/RunTaskResponse")]
        System.Threading.Tasks.Task<string> RunTaskAsync(int task_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBCIISServicesChannel : BlueCurve.Dataloader.AM.ServiceReference1.IBCIISServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BCIISServicesClient : System.ServiceModel.ClientBase<BlueCurve.Dataloader.AM.ServiceReference1.IBCIISServices>, BlueCurve.Dataloader.AM.ServiceReference1.IBCIISServices {
        
        public BCIISServicesClient() {
        }
        
        public BCIISServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BCIISServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BCIISServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BCIISServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AggregateUniverse(long run_id, long universe_id, int audit_id, System.DateTime audit_date) {
            return base.Channel.AggregateUniverse(run_id, universe_id, audit_id, audit_date);
        }
        
        public System.Threading.Tasks.Task<string> AggregateUniverseAsync(long run_id, long universe_id, int audit_id, System.DateTime audit_date) {
            return base.Channel.AggregateUniverseAsync(run_id, universe_id, audit_id, audit_date);
        }
        
        public BlueCurve.Dataloader.AM.ServiceReference1.agg_results AggregateUniverseDebug(long run_id, long universe_id, int audit_id, System.DateTime audit_date, long target_entity_id, long dual_entity_id, int debug_exch_method, string debug_calc_type, bool inc_constituents) {
            return base.Channel.AggregateUniverseDebug(run_id, universe_id, audit_id, audit_date, target_entity_id, dual_entity_id, debug_exch_method, debug_calc_type, inc_constituents);
        }
        
        public System.Threading.Tasks.Task<BlueCurve.Dataloader.AM.ServiceReference1.agg_results> AggregateUniverseDebugAsync(long run_id, long universe_id, int audit_id, System.DateTime audit_date, long target_entity_id, long dual_entity_id, int debug_exch_method, string debug_calc_type, bool inc_constituents) {
            return base.Channel.AggregateUniverseDebugAsync(run_id, universe_id, audit_id, audit_date, target_entity_id, dual_entity_id, debug_exch_method, debug_calc_type, inc_constituents);
        }
        
        public string CalcAll(long run_id, long entity_id, int audit_id, System.DateTime audit_date, int contributor_id) {
            return base.Channel.CalcAll(run_id, entity_id, audit_id, audit_date, contributor_id);
        }
        
        public System.Threading.Tasks.Task<string> CalcAllAsync(long run_id, long entity_id, int audit_id, System.DateTime audit_date, int contributor_id) {
            return base.Channel.CalcAllAsync(run_id, entity_id, audit_id, audit_date, contributor_id);
        }
        
        public string RunTask(int task_id) {
            return base.Channel.RunTask(task_id);
        }
        
        public System.Threading.Tasks.Task<string> RunTaskAsync(int task_id) {
            return base.Channel.RunTaskAsync(task_id);
        }
    }
}
