'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference2
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="agg_results", [Namespace]:="http://schemas.datacontract.org/2004/07/BlueCurve.IIS.Services"),  _
     System.SerializableAttribute()>  _
    Partial Public Class agg_results
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private abc_calc_aggField() As ServiceReference2.abc_calc_agg
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private abc_calc_agg_ccField() As ServiceReference2.abc_calc_agg
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private abc_calc_agg_growthsField() As ServiceReference2.abc_calc_agg
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private errorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private resultsField() As ServiceReference2.agg_result
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ttestField() As ServiceReference2.ttest_result
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property abc_calc_agg() As ServiceReference2.abc_calc_agg()
            Get
                Return Me.abc_calc_aggField
            End Get
            Set
                If (Object.ReferenceEquals(Me.abc_calc_aggField, value) <> true) Then
                    Me.abc_calc_aggField = value
                    Me.RaisePropertyChanged("abc_calc_agg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property abc_calc_agg_cc() As ServiceReference2.abc_calc_agg()
            Get
                Return Me.abc_calc_agg_ccField
            End Get
            Set
                If (Object.ReferenceEquals(Me.abc_calc_agg_ccField, value) <> true) Then
                    Me.abc_calc_agg_ccField = value
                    Me.RaisePropertyChanged("abc_calc_agg_cc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property abc_calc_agg_growths() As ServiceReference2.abc_calc_agg()
            Get
                Return Me.abc_calc_agg_growthsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.abc_calc_agg_growthsField, value) <> true) Then
                    Me.abc_calc_agg_growthsField = value
                    Me.RaisePropertyChanged("abc_calc_agg_growths")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [error]() As String
            Get
                Return Me.errorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.errorField, value) <> true) Then
                    Me.errorField = value
                    Me.RaisePropertyChanged("error")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property results() As ServiceReference2.agg_result()
            Get
                Return Me.resultsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.resultsField, value) <> true) Then
                    Me.resultsField = value
                    Me.RaisePropertyChanged("results")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ttest() As ServiceReference2.ttest_result()
            Get
                Return Me.ttestField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ttestField, value) <> true) Then
                    Me.ttestField = value
                    Me.RaisePropertyChanged("ttest")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="abc_calc_agg", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class abc_calc_agg
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private calculation_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private calenderized_year_offsetField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private class_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private contributor_1_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private contributor_2_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private contributor_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private dual_entity_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private entity_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private formulaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private host_curr_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private include_in_growthlField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private include_in_growthrField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private intervalField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private interval_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private item_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private num_yearsField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private op1_curr_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private op2_curr_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private op3_curr_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private op4_curr_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private op5_curr_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private op6_curr_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private op7_curr_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private op8_curr_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_1_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_1_is_weightField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_2_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_2_is_weightField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_3_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_3_is_weightField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_4_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_4_is_weightField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_5_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_5_is_weightField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_6_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_6_is_weightField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_7_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_7_is_weightField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_8_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private operand_8_is_weightField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private parent_entity_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private period_end_dateField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private period_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_1_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_2Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_2_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_3Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_3_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_4Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_4_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_5Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_5_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_6Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_6_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_7Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_7_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_8Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private raw_value_8_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private result_row_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private target_entity_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private value_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private value_2Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private value_3Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private value_4Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private value_5Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private value_6Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private value_7Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private value_8Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private value_8_1Field As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private weightingField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private workflow_stageField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private yearField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property calculation_id() As Long
            Get
                Return Me.calculation_idField
            End Get
            Set
                If (Me.calculation_idField.Equals(value) <> true) Then
                    Me.calculation_idField = value
                    Me.RaisePropertyChanged("calculation_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property calenderized_year_offset() As Integer
            Get
                Return Me.calenderized_year_offsetField
            End Get
            Set
                If (Me.calenderized_year_offsetField.Equals(value) <> true) Then
                    Me.calenderized_year_offsetField = value
                    Me.RaisePropertyChanged("calenderized_year_offset")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property class_id() As Long
            Get
                Return Me.class_idField
            End Get
            Set
                If (Me.class_idField.Equals(value) <> true) Then
                    Me.class_idField = value
                    Me.RaisePropertyChanged("class_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property contributor_1_id() As Long
            Get
                Return Me.contributor_1_idField
            End Get
            Set
                If (Me.contributor_1_idField.Equals(value) <> true) Then
                    Me.contributor_1_idField = value
                    Me.RaisePropertyChanged("contributor_1_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property contributor_2_id() As Long
            Get
                Return Me.contributor_2_idField
            End Get
            Set
                If (Me.contributor_2_idField.Equals(value) <> true) Then
                    Me.contributor_2_idField = value
                    Me.RaisePropertyChanged("contributor_2_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property contributor_id() As Integer
            Get
                Return Me.contributor_idField
            End Get
            Set
                If (Me.contributor_idField.Equals(value) <> true) Then
                    Me.contributor_idField = value
                    Me.RaisePropertyChanged("contributor_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property dual_entity_id() As Long
            Get
                Return Me.dual_entity_idField
            End Get
            Set
                If (Me.dual_entity_idField.Equals(value) <> true) Then
                    Me.dual_entity_idField = value
                    Me.RaisePropertyChanged("dual_entity_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property entity_id() As Long
            Get
                Return Me.entity_idField
            End Get
            Set
                If (Me.entity_idField.Equals(value) <> true) Then
                    Me.entity_idField = value
                    Me.RaisePropertyChanged("entity_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property formula() As String
            Get
                Return Me.formulaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.formulaField, value) <> true) Then
                    Me.formulaField = value
                    Me.RaisePropertyChanged("formula")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property host_curr_id() As Long
            Get
                Return Me.host_curr_idField
            End Get
            Set
                If (Me.host_curr_idField.Equals(value) <> true) Then
                    Me.host_curr_idField = value
                    Me.RaisePropertyChanged("host_curr_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property include_in_growthl() As Boolean
            Get
                Return Me.include_in_growthlField
            End Get
            Set
                If (Me.include_in_growthlField.Equals(value) <> true) Then
                    Me.include_in_growthlField = value
                    Me.RaisePropertyChanged("include_in_growthl")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property include_in_growthr() As Boolean
            Get
                Return Me.include_in_growthrField
            End Get
            Set
                If (Me.include_in_growthrField.Equals(value) <> true) Then
                    Me.include_in_growthrField = value
                    Me.RaisePropertyChanged("include_in_growthr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property interval() As Integer
            Get
                Return Me.intervalField
            End Get
            Set
                If (Me.intervalField.Equals(value) <> true) Then
                    Me.intervalField = value
                    Me.RaisePropertyChanged("interval")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property interval_type() As Integer
            Get
                Return Me.interval_typeField
            End Get
            Set
                If (Me.interval_typeField.Equals(value) <> true) Then
                    Me.interval_typeField = value
                    Me.RaisePropertyChanged("interval_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property item_id() As Integer
            Get
                Return Me.item_idField
            End Get
            Set
                If (Me.item_idField.Equals(value) <> true) Then
                    Me.item_idField = value
                    Me.RaisePropertyChanged("item_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property num_years() As Integer
            Get
                Return Me.num_yearsField
            End Get
            Set
                If (Me.num_yearsField.Equals(value) <> true) Then
                    Me.num_yearsField = value
                    Me.RaisePropertyChanged("num_years")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property op1_curr_type() As Integer
            Get
                Return Me.op1_curr_typeField
            End Get
            Set
                If (Me.op1_curr_typeField.Equals(value) <> true) Then
                    Me.op1_curr_typeField = value
                    Me.RaisePropertyChanged("op1_curr_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property op2_curr_type() As Integer
            Get
                Return Me.op2_curr_typeField
            End Get
            Set
                If (Me.op2_curr_typeField.Equals(value) <> true) Then
                    Me.op2_curr_typeField = value
                    Me.RaisePropertyChanged("op2_curr_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property op3_curr_type() As Integer
            Get
                Return Me.op3_curr_typeField
            End Get
            Set
                If (Me.op3_curr_typeField.Equals(value) <> true) Then
                    Me.op3_curr_typeField = value
                    Me.RaisePropertyChanged("op3_curr_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property op4_curr_type() As Integer
            Get
                Return Me.op4_curr_typeField
            End Get
            Set
                If (Me.op4_curr_typeField.Equals(value) <> true) Then
                    Me.op4_curr_typeField = value
                    Me.RaisePropertyChanged("op4_curr_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property op5_curr_type() As Integer
            Get
                Return Me.op5_curr_typeField
            End Get
            Set
                If (Me.op5_curr_typeField.Equals(value) <> true) Then
                    Me.op5_curr_typeField = value
                    Me.RaisePropertyChanged("op5_curr_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property op6_curr_type() As Integer
            Get
                Return Me.op6_curr_typeField
            End Get
            Set
                If (Me.op6_curr_typeField.Equals(value) <> true) Then
                    Me.op6_curr_typeField = value
                    Me.RaisePropertyChanged("op6_curr_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property op7_curr_type() As Integer
            Get
                Return Me.op7_curr_typeField
            End Get
            Set
                If (Me.op7_curr_typeField.Equals(value) <> true) Then
                    Me.op7_curr_typeField = value
                    Me.RaisePropertyChanged("op7_curr_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property op8_curr_type() As Integer
            Get
                Return Me.op8_curr_typeField
            End Get
            Set
                If (Me.op8_curr_typeField.Equals(value) <> true) Then
                    Me.op8_curr_typeField = value
                    Me.RaisePropertyChanged("op8_curr_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_1_id() As Long
            Get
                Return Me.operand_1_idField
            End Get
            Set
                If (Me.operand_1_idField.Equals(value) <> true) Then
                    Me.operand_1_idField = value
                    Me.RaisePropertyChanged("operand_1_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_1_is_weight() As Boolean
            Get
                Return Me.operand_1_is_weightField
            End Get
            Set
                If (Me.operand_1_is_weightField.Equals(value) <> true) Then
                    Me.operand_1_is_weightField = value
                    Me.RaisePropertyChanged("operand_1_is_weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_2_id() As Long
            Get
                Return Me.operand_2_idField
            End Get
            Set
                If (Me.operand_2_idField.Equals(value) <> true) Then
                    Me.operand_2_idField = value
                    Me.RaisePropertyChanged("operand_2_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_2_is_weight() As Boolean
            Get
                Return Me.operand_2_is_weightField
            End Get
            Set
                If (Me.operand_2_is_weightField.Equals(value) <> true) Then
                    Me.operand_2_is_weightField = value
                    Me.RaisePropertyChanged("operand_2_is_weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_3_id() As Long
            Get
                Return Me.operand_3_idField
            End Get
            Set
                If (Me.operand_3_idField.Equals(value) <> true) Then
                    Me.operand_3_idField = value
                    Me.RaisePropertyChanged("operand_3_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_3_is_weight() As Boolean
            Get
                Return Me.operand_3_is_weightField
            End Get
            Set
                If (Me.operand_3_is_weightField.Equals(value) <> true) Then
                    Me.operand_3_is_weightField = value
                    Me.RaisePropertyChanged("operand_3_is_weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_4_id() As Long
            Get
                Return Me.operand_4_idField
            End Get
            Set
                If (Me.operand_4_idField.Equals(value) <> true) Then
                    Me.operand_4_idField = value
                    Me.RaisePropertyChanged("operand_4_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_4_is_weight() As Boolean
            Get
                Return Me.operand_4_is_weightField
            End Get
            Set
                If (Me.operand_4_is_weightField.Equals(value) <> true) Then
                    Me.operand_4_is_weightField = value
                    Me.RaisePropertyChanged("operand_4_is_weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_5_id() As Long
            Get
                Return Me.operand_5_idField
            End Get
            Set
                If (Me.operand_5_idField.Equals(value) <> true) Then
                    Me.operand_5_idField = value
                    Me.RaisePropertyChanged("operand_5_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_5_is_weight() As Boolean
            Get
                Return Me.operand_5_is_weightField
            End Get
            Set
                If (Me.operand_5_is_weightField.Equals(value) <> true) Then
                    Me.operand_5_is_weightField = value
                    Me.RaisePropertyChanged("operand_5_is_weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_6_id() As Long
            Get
                Return Me.operand_6_idField
            End Get
            Set
                If (Me.operand_6_idField.Equals(value) <> true) Then
                    Me.operand_6_idField = value
                    Me.RaisePropertyChanged("operand_6_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_6_is_weight() As Boolean
            Get
                Return Me.operand_6_is_weightField
            End Get
            Set
                If (Me.operand_6_is_weightField.Equals(value) <> true) Then
                    Me.operand_6_is_weightField = value
                    Me.RaisePropertyChanged("operand_6_is_weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_7_id() As Long
            Get
                Return Me.operand_7_idField
            End Get
            Set
                If (Me.operand_7_idField.Equals(value) <> true) Then
                    Me.operand_7_idField = value
                    Me.RaisePropertyChanged("operand_7_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_7_is_weight() As Boolean
            Get
                Return Me.operand_7_is_weightField
            End Get
            Set
                If (Me.operand_7_is_weightField.Equals(value) <> true) Then
                    Me.operand_7_is_weightField = value
                    Me.RaisePropertyChanged("operand_7_is_weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_8_id() As Long
            Get
                Return Me.operand_8_idField
            End Get
            Set
                If (Me.operand_8_idField.Equals(value) <> true) Then
                    Me.operand_8_idField = value
                    Me.RaisePropertyChanged("operand_8_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property operand_8_is_weight() As Boolean
            Get
                Return Me.operand_8_is_weightField
            End Get
            Set
                If (Me.operand_8_is_weightField.Equals(value) <> true) Then
                    Me.operand_8_is_weightField = value
                    Me.RaisePropertyChanged("operand_8_is_weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property parent_entity_id() As Long
            Get
                Return Me.parent_entity_idField
            End Get
            Set
                If (Me.parent_entity_idField.Equals(value) <> true) Then
                    Me.parent_entity_idField = value
                    Me.RaisePropertyChanged("parent_entity_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property period_end_date() As Date
            Get
                Return Me.period_end_dateField
            End Get
            Set
                If (Me.period_end_dateField.Equals(value) <> true) Then
                    Me.period_end_dateField = value
                    Me.RaisePropertyChanged("period_end_date")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property period_id() As Integer
            Get
                Return Me.period_idField
            End Get
            Set
                If (Me.period_idField.Equals(value) <> true) Then
                    Me.period_idField = value
                    Me.RaisePropertyChanged("period_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_1() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_1Field
            End Get
            Set
                If (Me.raw_value_1Field.Equals(value) <> true) Then
                    Me.raw_value_1Field = value
                    Me.RaisePropertyChanged("raw_value_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_1_1() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_1_1Field
            End Get
            Set
                If (Me.raw_value_1_1Field.Equals(value) <> true) Then
                    Me.raw_value_1_1Field = value
                    Me.RaisePropertyChanged("raw_value_1_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_2() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_2Field
            End Get
            Set
                If (Me.raw_value_2Field.Equals(value) <> true) Then
                    Me.raw_value_2Field = value
                    Me.RaisePropertyChanged("raw_value_2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_2_1() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_2_1Field
            End Get
            Set
                If (Me.raw_value_2_1Field.Equals(value) <> true) Then
                    Me.raw_value_2_1Field = value
                    Me.RaisePropertyChanged("raw_value_2_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_3() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_3Field
            End Get
            Set
                If (Me.raw_value_3Field.Equals(value) <> true) Then
                    Me.raw_value_3Field = value
                    Me.RaisePropertyChanged("raw_value_3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_3_1() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_3_1Field
            End Get
            Set
                If (Me.raw_value_3_1Field.Equals(value) <> true) Then
                    Me.raw_value_3_1Field = value
                    Me.RaisePropertyChanged("raw_value_3_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_4() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_4Field
            End Get
            Set
                If (Me.raw_value_4Field.Equals(value) <> true) Then
                    Me.raw_value_4Field = value
                    Me.RaisePropertyChanged("raw_value_4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_4_1() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_4_1Field
            End Get
            Set
                If (Me.raw_value_4_1Field.Equals(value) <> true) Then
                    Me.raw_value_4_1Field = value
                    Me.RaisePropertyChanged("raw_value_4_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_5() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_5Field
            End Get
            Set
                If (Me.raw_value_5Field.Equals(value) <> true) Then
                    Me.raw_value_5Field = value
                    Me.RaisePropertyChanged("raw_value_5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_5_1() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_5_1Field
            End Get
            Set
                If (Me.raw_value_5_1Field.Equals(value) <> true) Then
                    Me.raw_value_5_1Field = value
                    Me.RaisePropertyChanged("raw_value_5_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_6() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_6Field
            End Get
            Set
                If (Me.raw_value_6Field.Equals(value) <> true) Then
                    Me.raw_value_6Field = value
                    Me.RaisePropertyChanged("raw_value_6")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_6_1() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_6_1Field
            End Get
            Set
                If (Me.raw_value_6_1Field.Equals(value) <> true) Then
                    Me.raw_value_6_1Field = value
                    Me.RaisePropertyChanged("raw_value_6_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_7() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_7Field
            End Get
            Set
                If (Me.raw_value_7Field.Equals(value) <> true) Then
                    Me.raw_value_7Field = value
                    Me.RaisePropertyChanged("raw_value_7")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_7_1() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_7_1Field
            End Get
            Set
                If (Me.raw_value_7_1Field.Equals(value) <> true) Then
                    Me.raw_value_7_1Field = value
                    Me.RaisePropertyChanged("raw_value_7_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_8() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_8Field
            End Get
            Set
                If (Me.raw_value_8Field.Equals(value) <> true) Then
                    Me.raw_value_8Field = value
                    Me.RaisePropertyChanged("raw_value_8")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property raw_value_8_1() As System.Nullable(Of Decimal)
            Get
                Return Me.raw_value_8_1Field
            End Get
            Set
                If (Me.raw_value_8_1Field.Equals(value) <> true) Then
                    Me.raw_value_8_1Field = value
                    Me.RaisePropertyChanged("raw_value_8_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property result_row_id() As Long
            Get
                Return Me.result_row_idField
            End Get
            Set
                If (Me.result_row_idField.Equals(value) <> true) Then
                    Me.result_row_idField = value
                    Me.RaisePropertyChanged("result_row_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property target_entity_id() As Long
            Get
                Return Me.target_entity_idField
            End Get
            Set
                If (Me.target_entity_idField.Equals(value) <> true) Then
                    Me.target_entity_idField = value
                    Me.RaisePropertyChanged("target_entity_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value_1() As System.Nullable(Of Decimal)
            Get
                Return Me.value_1Field
            End Get
            Set
                If (Me.value_1Field.Equals(value) <> true) Then
                    Me.value_1Field = value
                    Me.RaisePropertyChanged("value_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value_2() As System.Nullable(Of Decimal)
            Get
                Return Me.value_2Field
            End Get
            Set
                If (Me.value_2Field.Equals(value) <> true) Then
                    Me.value_2Field = value
                    Me.RaisePropertyChanged("value_2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value_3() As System.Nullable(Of Decimal)
            Get
                Return Me.value_3Field
            End Get
            Set
                If (Me.value_3Field.Equals(value) <> true) Then
                    Me.value_3Field = value
                    Me.RaisePropertyChanged("value_3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value_4() As System.Nullable(Of Decimal)
            Get
                Return Me.value_4Field
            End Get
            Set
                If (Me.value_4Field.Equals(value) <> true) Then
                    Me.value_4Field = value
                    Me.RaisePropertyChanged("value_4")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value_5() As System.Nullable(Of Decimal)
            Get
                Return Me.value_5Field
            End Get
            Set
                If (Me.value_5Field.Equals(value) <> true) Then
                    Me.value_5Field = value
                    Me.RaisePropertyChanged("value_5")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value_6() As System.Nullable(Of Decimal)
            Get
                Return Me.value_6Field
            End Get
            Set
                If (Me.value_6Field.Equals(value) <> true) Then
                    Me.value_6Field = value
                    Me.RaisePropertyChanged("value_6")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value_7() As System.Nullable(Of Decimal)
            Get
                Return Me.value_7Field
            End Get
            Set
                If (Me.value_7Field.Equals(value) <> true) Then
                    Me.value_7Field = value
                    Me.RaisePropertyChanged("value_7")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value_8() As System.Nullable(Of Decimal)
            Get
                Return Me.value_8Field
            End Get
            Set
                If (Me.value_8Field.Equals(value) <> true) Then
                    Me.value_8Field = value
                    Me.RaisePropertyChanged("value_8")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value_8_1() As System.Nullable(Of Decimal)
            Get
                Return Me.value_8_1Field
            End Get
            Set
                If (Me.value_8_1Field.Equals(value) <> true) Then
                    Me.value_8_1Field = value
                    Me.RaisePropertyChanged("value_8_1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property weighting() As System.Nullable(Of Decimal)
            Get
                Return Me.weightingField
            End Get
            Set
                If (Me.weightingField.Equals(value) <> true) Then
                    Me.weightingField = value
                    Me.RaisePropertyChanged("weighting")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property workflow_stage() As Integer
            Get
                Return Me.workflow_stageField
            End Get
            Set
                If (Me.workflow_stageField.Equals(value) <> true) Then
                    Me.workflow_stageField = value
                    Me.RaisePropertyChanged("workflow_stage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property year() As Integer
            Get
                Return Me.yearField
            End Get
            Set
                If (Me.yearField.Equals(value) <> true) Then
                    Me.yearField = value
                    Me.RaisePropertyChanged("year")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="agg_result", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class agg_result
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private audit_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private contributor_1_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private contributor_2_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private contributor_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private currencyField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private dual_entity_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private exch_typeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private item_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private lvalueField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private num_yearsField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private period_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private rvalueField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private target_entity_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private universe_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private valueField As System.Nullable(Of Decimal)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private workflow_stageField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private yearField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property audit_id() As Long
            Get
                Return Me.audit_idField
            End Get
            Set
                If (Me.audit_idField.Equals(value) <> true) Then
                    Me.audit_idField = value
                    Me.RaisePropertyChanged("audit_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property contributor_1_id() As Long
            Get
                Return Me.contributor_1_idField
            End Get
            Set
                If (Me.contributor_1_idField.Equals(value) <> true) Then
                    Me.contributor_1_idField = value
                    Me.RaisePropertyChanged("contributor_1_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property contributor_2_id() As Long
            Get
                Return Me.contributor_2_idField
            End Get
            Set
                If (Me.contributor_2_idField.Equals(value) <> true) Then
                    Me.contributor_2_idField = value
                    Me.RaisePropertyChanged("contributor_2_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property contributor_id() As Integer
            Get
                Return Me.contributor_idField
            End Get
            Set
                If (Me.contributor_idField.Equals(value) <> true) Then
                    Me.contributor_idField = value
                    Me.RaisePropertyChanged("contributor_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property currency() As Long
            Get
                Return Me.currencyField
            End Get
            Set
                If (Me.currencyField.Equals(value) <> true) Then
                    Me.currencyField = value
                    Me.RaisePropertyChanged("currency")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property dual_entity_id() As Long
            Get
                Return Me.dual_entity_idField
            End Get
            Set
                If (Me.dual_entity_idField.Equals(value) <> true) Then
                    Me.dual_entity_idField = value
                    Me.RaisePropertyChanged("dual_entity_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property exch_type() As Integer
            Get
                Return Me.exch_typeField
            End Get
            Set
                If (Me.exch_typeField.Equals(value) <> true) Then
                    Me.exch_typeField = value
                    Me.RaisePropertyChanged("exch_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property item_id() As Long
            Get
                Return Me.item_idField
            End Get
            Set
                If (Me.item_idField.Equals(value) <> true) Then
                    Me.item_idField = value
                    Me.RaisePropertyChanged("item_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property lvalue() As System.Nullable(Of Decimal)
            Get
                Return Me.lvalueField
            End Get
            Set
                If (Me.lvalueField.Equals(value) <> true) Then
                    Me.lvalueField = value
                    Me.RaisePropertyChanged("lvalue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property num_years() As Integer
            Get
                Return Me.num_yearsField
            End Get
            Set
                If (Me.num_yearsField.Equals(value) <> true) Then
                    Me.num_yearsField = value
                    Me.RaisePropertyChanged("num_years")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property period_id() As Integer
            Get
                Return Me.period_idField
            End Get
            Set
                If (Me.period_idField.Equals(value) <> true) Then
                    Me.period_idField = value
                    Me.RaisePropertyChanged("period_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property rvalue() As System.Nullable(Of Decimal)
            Get
                Return Me.rvalueField
            End Get
            Set
                If (Me.rvalueField.Equals(value) <> true) Then
                    Me.rvalueField = value
                    Me.RaisePropertyChanged("rvalue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property target_entity_id() As Long
            Get
                Return Me.target_entity_idField
            End Get
            Set
                If (Me.target_entity_idField.Equals(value) <> true) Then
                    Me.target_entity_idField = value
                    Me.RaisePropertyChanged("target_entity_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property universe_id() As Long
            Get
                Return Me.universe_idField
            End Get
            Set
                If (Me.universe_idField.Equals(value) <> true) Then
                    Me.universe_idField = value
                    Me.RaisePropertyChanged("universe_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value() As System.Nullable(Of Decimal)
            Get
                Return Me.valueField
            End Get
            Set
                If (Me.valueField.Equals(value) <> true) Then
                    Me.valueField = value
                    Me.RaisePropertyChanged("value")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property workflow_stage() As Integer
            Get
                Return Me.workflow_stageField
            End Get
            Set
                If (Me.workflow_stageField.Equals(value) <> true) Then
                    Me.workflow_stageField = value
                    Me.RaisePropertyChanged("workflow_stage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property year() As Integer
            Get
                Return Me.yearField
            End Get
            Set
                If (Me.yearField.Equals(value) <> true) Then
                    Me.yearField = value
                    Me.RaisePropertyChanged("year")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ttest_result", [Namespace]:="http://schemas.datacontract.org/2004/07/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ttest_result
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private contributor_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private eff_numberField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private item_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private meanField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private num_pointsField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private period_idField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private sd3Field As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private standard_deviationField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private standard_deviation_multField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private style_calculation_typeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private total_weightField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private weighted_meanField As Double
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private workflow_stageField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private yearField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property contributor_id() As Integer
            Get
                Return Me.contributor_idField
            End Get
            Set
                If (Me.contributor_idField.Equals(value) <> true) Then
                    Me.contributor_idField = value
                    Me.RaisePropertyChanged("contributor_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property eff_number() As Double
            Get
                Return Me.eff_numberField
            End Get
            Set
                If (Me.eff_numberField.Equals(value) <> true) Then
                    Me.eff_numberField = value
                    Me.RaisePropertyChanged("eff_number")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property item_id() As Long
            Get
                Return Me.item_idField
            End Get
            Set
                If (Me.item_idField.Equals(value) <> true) Then
                    Me.item_idField = value
                    Me.RaisePropertyChanged("item_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property mean() As Decimal
            Get
                Return Me.meanField
            End Get
            Set
                If (Me.meanField.Equals(value) <> true) Then
                    Me.meanField = value
                    Me.RaisePropertyChanged("mean")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property num_points() As Integer
            Get
                Return Me.num_pointsField
            End Get
            Set
                If (Me.num_pointsField.Equals(value) <> true) Then
                    Me.num_pointsField = value
                    Me.RaisePropertyChanged("num_points")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property period_id() As Integer
            Get
                Return Me.period_idField
            End Get
            Set
                If (Me.period_idField.Equals(value) <> true) Then
                    Me.period_idField = value
                    Me.RaisePropertyChanged("period_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property sd3() As Double
            Get
                Return Me.sd3Field
            End Get
            Set
                If (Me.sd3Field.Equals(value) <> true) Then
                    Me.sd3Field = value
                    Me.RaisePropertyChanged("sd3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property standard_deviation() As Double
            Get
                Return Me.standard_deviationField
            End Get
            Set
                If (Me.standard_deviationField.Equals(value) <> true) Then
                    Me.standard_deviationField = value
                    Me.RaisePropertyChanged("standard_deviation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property standard_deviation_mult() As Double
            Get
                Return Me.standard_deviation_multField
            End Get
            Set
                If (Me.standard_deviation_multField.Equals(value) <> true) Then
                    Me.standard_deviation_multField = value
                    Me.RaisePropertyChanged("standard_deviation_mult")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property style_calculation_type() As String
            Get
                Return Me.style_calculation_typeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.style_calculation_typeField, value) <> true) Then
                    Me.style_calculation_typeField = value
                    Me.RaisePropertyChanged("style_calculation_type")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property total_weight() As Decimal
            Get
                Return Me.total_weightField
            End Get
            Set
                If (Me.total_weightField.Equals(value) <> true) Then
                    Me.total_weightField = value
                    Me.RaisePropertyChanged("total_weight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property weighted_mean() As Double
            Get
                Return Me.weighted_meanField
            End Get
            Set
                If (Me.weighted_meanField.Equals(value) <> true) Then
                    Me.weighted_meanField = value
                    Me.RaisePropertyChanged("weighted_mean")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property workflow_stage() As Integer
            Get
                Return Me.workflow_stageField
            End Get
            Set
                If (Me.workflow_stageField.Equals(value) <> true) Then
                    Me.workflow_stageField = value
                    Me.RaisePropertyChanged("workflow_stage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property year() As Integer
            Get
                Return Me.yearField
            End Get
            Set
                If (Me.yearField.Equals(value) <> true) Then
                    Me.yearField = value
                    Me.RaisePropertyChanged("year")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference2.IBCIISServices")>  _
    Public Interface IBCIISServices
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/AggregateUniverse", ReplyAction:="http://tempuri.org/IBCIISServices/AggregateUniverseResponse")>  _
        Function AggregateUniverse(ByVal run_id As Long, ByVal universe_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/AggregateUniverse", ReplyAction:="http://tempuri.org/IBCIISServices/AggregateUniverseResponse")>  _
        Function AggregateUniverseAsync(ByVal run_id As Long, ByVal universe_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/AggregateUniverseDebug", ReplyAction:="http://tempuri.org/IBCIISServices/AggregateUniverseDebugResponse")>  _
        Function AggregateUniverseDebug(ByVal run_id As Long, ByVal universe_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date, ByVal target_entity_id As Long, ByVal dual_entity_id As Long, ByVal debug_exch_method As Integer, ByVal debug_calc_type As String, ByVal inc_constituents As Boolean) As ServiceReference2.agg_results
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/AggregateUniverseDebug", ReplyAction:="http://tempuri.org/IBCIISServices/AggregateUniverseDebugResponse")>  _
        Function AggregateUniverseDebugAsync(ByVal run_id As Long, ByVal universe_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date, ByVal target_entity_id As Long, ByVal dual_entity_id As Long, ByVal debug_exch_method As Integer, ByVal debug_calc_type As String, ByVal inc_constituents As Boolean) As System.Threading.Tasks.Task(Of ServiceReference2.agg_results)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/CalcAll", ReplyAction:="http://tempuri.org/IBCIISServices/CalcAllResponse")>  _
        Function CalcAll(ByVal run_id As Long, ByVal entity_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date, ByVal contributor_id As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/CalcAll", ReplyAction:="http://tempuri.org/IBCIISServices/CalcAllResponse")>  _
        Function CalcAllAsync(ByVal run_id As Long, ByVal entity_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date, ByVal contributor_id As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/RunTask", ReplyAction:="http://tempuri.org/IBCIISServices/RunTaskResponse")>  _
        Function RunTask(ByVal task_id As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/RunTask", ReplyAction:="http://tempuri.org/IBCIISServices/RunTaskResponse")>  _
        Function RunTaskAsync(ByVal task_id As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/SendEmail", ReplyAction:="http://tempuri.org/IBCIISServices/SendEmailResponse")>  _
        Function SendEmail(ByVal id As Long, ByVal use_bcc As Boolean, ByVal title As String, ByVal body As String, ByVal title_template_Id As Integer, ByVal body_template_id As Integer, ByVal doc_Id As Long, ByVal entity_Id As Long, ByVal user_id As Long, ByVal stage_id As Long, ByVal digest1 As Long, ByVal digest2 As Long) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IBCIISServices/SendEmail", ReplyAction:="http://tempuri.org/IBCIISServices/SendEmailResponse")>  _
        Function SendEmailAsync(ByVal id As Long, ByVal use_bcc As Boolean, ByVal title As String, ByVal body As String, ByVal title_template_Id As Integer, ByVal body_template_id As Integer, ByVal doc_Id As Long, ByVal entity_Id As Long, ByVal user_id As Long, ByVal stage_id As Long, ByVal digest1 As Long, ByVal digest2 As Long) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IBCIISServicesChannel
        Inherits ServiceReference2.IBCIISServices, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class BCIISServicesClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference2.IBCIISServices)
        Implements ServiceReference2.IBCIISServices
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function AggregateUniverse(ByVal run_id As Long, ByVal universe_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date) As String Implements ServiceReference2.IBCIISServices.AggregateUniverse
            Return MyBase.Channel.AggregateUniverse(run_id, universe_id, audit_id, audit_date)
        End Function
        
        Public Function AggregateUniverseAsync(ByVal run_id As Long, ByVal universe_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date) As System.Threading.Tasks.Task(Of String) Implements ServiceReference2.IBCIISServices.AggregateUniverseAsync
            Return MyBase.Channel.AggregateUniverseAsync(run_id, universe_id, audit_id, audit_date)
        End Function
        
        Public Function AggregateUniverseDebug(ByVal run_id As Long, ByVal universe_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date, ByVal target_entity_id As Long, ByVal dual_entity_id As Long, ByVal debug_exch_method As Integer, ByVal debug_calc_type As String, ByVal inc_constituents As Boolean) As ServiceReference2.agg_results Implements ServiceReference2.IBCIISServices.AggregateUniverseDebug
            Return MyBase.Channel.AggregateUniverseDebug(run_id, universe_id, audit_id, audit_date, target_entity_id, dual_entity_id, debug_exch_method, debug_calc_type, inc_constituents)
        End Function
        
        Public Function AggregateUniverseDebugAsync(ByVal run_id As Long, ByVal universe_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date, ByVal target_entity_id As Long, ByVal dual_entity_id As Long, ByVal debug_exch_method As Integer, ByVal debug_calc_type As String, ByVal inc_constituents As Boolean) As System.Threading.Tasks.Task(Of ServiceReference2.agg_results) Implements ServiceReference2.IBCIISServices.AggregateUniverseDebugAsync
            Return MyBase.Channel.AggregateUniverseDebugAsync(run_id, universe_id, audit_id, audit_date, target_entity_id, dual_entity_id, debug_exch_method, debug_calc_type, inc_constituents)
        End Function
        
        Public Function CalcAll(ByVal run_id As Long, ByVal entity_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date, ByVal contributor_id As Integer) As String Implements ServiceReference2.IBCIISServices.CalcAll
            Return MyBase.Channel.CalcAll(run_id, entity_id, audit_id, audit_date, contributor_id)
        End Function
        
        Public Function CalcAllAsync(ByVal run_id As Long, ByVal entity_id As Long, ByVal audit_id As Integer, ByVal audit_date As Date, ByVal contributor_id As Integer) As System.Threading.Tasks.Task(Of String) Implements ServiceReference2.IBCIISServices.CalcAllAsync
            Return MyBase.Channel.CalcAllAsync(run_id, entity_id, audit_id, audit_date, contributor_id)
        End Function
        
        Public Function RunTask(ByVal task_id As Integer) As String Implements ServiceReference2.IBCIISServices.RunTask
            Return MyBase.Channel.RunTask(task_id)
        End Function
        
        Public Function RunTaskAsync(ByVal task_id As Integer) As System.Threading.Tasks.Task(Of String) Implements ServiceReference2.IBCIISServices.RunTaskAsync
            Return MyBase.Channel.RunTaskAsync(task_id)
        End Function
        
        Public Function SendEmail(ByVal id As Long, ByVal use_bcc As Boolean, ByVal title As String, ByVal body As String, ByVal title_template_Id As Integer, ByVal body_template_id As Integer, ByVal doc_Id As Long, ByVal entity_Id As Long, ByVal user_id As Long, ByVal stage_id As Long, ByVal digest1 As Long, ByVal digest2 As Long) As String Implements ServiceReference2.IBCIISServices.SendEmail
            Return MyBase.Channel.SendEmail(id, use_bcc, title, body, title_template_Id, body_template_id, doc_Id, entity_Id, user_id, stage_id, digest1, digest2)
        End Function
        
        Public Function SendEmailAsync(ByVal id As Long, ByVal use_bcc As Boolean, ByVal title As String, ByVal body As String, ByVal title_template_Id As Integer, ByVal body_template_id As Integer, ByVal doc_Id As Long, ByVal entity_Id As Long, ByVal user_id As Long, ByVal stage_id As Long, ByVal digest1 As Long, ByVal digest2 As Long) As System.Threading.Tasks.Task(Of String) Implements ServiceReference2.IBCIISServices.SendEmailAsync
            Return MyBase.Channel.SendEmailAsync(id, use_bcc, title, body, title_template_Id, body_template_id, doc_Id, entity_Id, user_id, stage_id, digest1, digest2)
        End Function
    End Class
End Namespace
